In [ ]:
# Do not modify the code in this cell.

%reset -f

from sys import path
path.append('../')

from helpers.submitters import TaskSubmitter

## Task 15.3: From XML To SQLite

Parse the iTunes export `library.xml` file and produce a properly normalized database with this structure:

```sql
CREATE TABLE artist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE album (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    artist_id INTEGER NOT NULL
);

CREATE TABLE genre (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE track (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    artist_id INTEGER NOT NULL,
    album_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    length SMALLINT,
    count SMALLINT DEFAULT 0,
    rating TINYINT DEFAULT -1
);
```

Use [`executescript`](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executescript) method to run multiple SQL statements with one call.

Use [`plistlib`](https://docs.python.org/3/library/plistlib.html) module to easily parse Apple XML files.

Return the result of the following SQL statement:

```sql
SELECT track.title, artist.name, album.title, genre.name
FROM track JOIN genre JOIN album JOIN artist
ON track.genre_id = genre.id AND
   track.album_id = album.id AND
   album.artist_id = artist.id
WHERE track.rating = -1
ORDER BY artist.name
LIMIT 3
```

---

After running the cell, you should see the following output:

```
[('D.T.', 'AC/DC', 'Who Made Who', 'Rock'),
 ('Sink the Pink', 'AC/DC', 'Who Made Who', 'Rock'),
 ('Ride On', 'AC/DC', 'Who Made Who', 'Rock')]
```

In [ ]:
# Modify the code only in the "YOUR CODE HERE" block.

import plistlib
import sqlite3


def foo():
    tables_sql = """
CREATE TABLE artist (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE album (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    artist_id INTEGER NOT NULL
);

CREATE TABLE genre (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE track (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title VARCHAR(255) NOT NULL UNIQUE,
    artist_id INTEGER NOT NULL,
    album_id INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    length SMALLINT,
    count SMALLINT DEFAULT 0,
    rating TINYINT DEFAULT -1
);
"""

    result_sql = """
SELECT track.title, artist.name, album.title, genre.name
FROM track JOIN genre JOIN album JOIN artist
ON track.genre_id = genre.id AND
   track.album_id = album.id AND
   album.artist_id = artist.id
WHERE track.rating = -1
ORDER BY artist.name
LIMIT 3
"""

    with open("library.xml", "rb") as xml:
        library = plistlib.load(xml)

    with sqlite3.connect(":memory:") as connection:
        cursor = connection.cursor()
        cursor.executescript(tables_sql)

        for track in library["Tracks"].values():
            
            # ========== YOUR CODE HERE ==========
            
            
            
        # ====================================

        return cursor.execute(result_sql).fetchall()


foo()

### Submit

In [ ]:
# Do not modify the code in this cell.

with TaskSubmitter("15.3", "return") as submitter:
    submitter.submit(foo)